# Netlify configuration with adaptive build script
[build]
  base = "/"
  command = "chmod +x ./build.sh && ./build.sh"
  publish = "Codes/jobmate/out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Explicitly handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Set cache headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
